# This is a configuration file for the release-drafter workflow

name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
  - title: Other Changes
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'publish'
    body:
      - 'r-publish'
    title:
      - 'r-publish'
  - label: 'major'
    body:
      - '/v-major/i'
    title:
      - '/v-major/i'
  - label: 'minor'
    body:
      - '/v-minor/i'
    title:
      - '/v-minor/i'
  - label: 'patch'
    body:
      - '/v-patch/i'
    title:
      - '/v-patch/i'
  - label: 'chore'
    title:
      - 'chore'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    body:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
template: |
  ## What's Changed

  $CHANGES

  ## Changelog
  https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
